# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 915ae4056836a13ae7a518e09ad69abd0947d1a2dc4dd84ff67b9bc26b7cdb07ce7dec630cffc442cfcb0b9192761dd826bedec297fd8cb8644d6674c37666fb

test:
  secret_key_base: f16ce630bb22ca5f18a5ef2dbb4e731dcec1277d8d87f9b74bbbe6ce8ade1c934aebcde1a36cf6ff72138b42a4b76d0074e2ea6f2b5dd0a49e23767d9e0cf6c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
